[package]
name = "uefi_app"
version = "0.1.0"
edition = "2018"

[dependencies]
# In a real application, change these to point to the latest release
# on crates.io.
uefi = { path = "..", features = ["exts"] }
uefi-services = { path = "../uefi-services" }
