[workspace]
resolver = "3"
members = [
    "template",
    "uefi",
    "uefi-macros",
    "uefi-raw",
    "uefi-std-example",
    "uefi-test-runner",
    "xtask",
]

[workspace.package]
authors = ["The Rust OSDev team"]
categories = ["embedded", "no-std", "api-bindings"]
edition = "2024"
keywords = ["uefi", "efi"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-osdev/uefi-rs"
rust-version = "1.91"

[workspace.dependencies]
bitflags = "2.0.0"
log = { version = "0.4.5", default-features = false }
jiff = { version = "0.2", default-features = false }
ptr_meta = { version = "0.3.0", default-features = false, features = ["derive"] }
qemu-exit = { version = "4.0.0" }
time = { version = "0.3", default-features = false }
uguid = "2.2.1"

[workspace.lints]
clippy = {
  # Groups
  "all" = "deny",

  # Individual
  "absolute_paths" = "deny",
  "missing_const_for_fn" = "deny",
  "missing_safety_doc" = "deny",
  "must_use_candidate" = "deny",
  "ptr_as_ptr" = "deny",
  "ref_as_ptr" = "deny",
  "undocumented_unsafe_blocks" = "deny",
  "use_self" = "deny",
}
rust = {
  "missing_debug_implementations" = "deny",
  "missing_docs" = "deny",
  "unsafe_op_in_unsafe_fn" = "deny",
  "unused" = "deny",
}

[patch.crates-io]
uefi = { path = "uefi" }
uefi-macros = { path = "uefi-macros" }
uefi-raw = { path = "uefi-raw" }

# Enable optimization for xtask itself, not for its dependencies. This speeds up
# OVMF prebuilt decompression without much increase in compilation time.
[profile.dev.package.xtask]
opt-level = 3
