[package]
name = "uefi-raw"
version = "0.15.1"
readme = "README.md"
description = """
Raw UEFI types and bindings for protocols, boot services, and runtime services.
They can serve as a base for UEFI firmware implementations or high-level
wrappers.
"""

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
# uefi-raw is much less likely to need the latest bleeding-edge features.
# Hence, it is okay to not use the workspace MSRV.
rust-version = "1.85.1"

[dependencies]
bitflags.workspace = true
uguid.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
