// SPDX-License-Identifier: MIT OR Apache-2.0

//! Metadata about every UEFI protocol defined in the specification.
//!
//! Includes each protocol's canonical name, GUID, and summary text, and
//! provides a way to look up that information by GUID.

use uguid::Guid;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct UEFIProtocolInfo {
    name: &'static str,
    guid: Guid,
    summary: &'static str,
}
impl UEFIProtocolInfo {
    pub const fn name(&self) -> &'static str {
        self.name
    }
    pub const fn guid(&self) -> Guid {
        self.guid
    }
    pub const fn summary(&self) -> &'static str {
        self.summary
    }
}

macro_rules! define_protocols {
    ($($canonical_name:ident => $uuid:literal => $summary:literal,)*) => {
        $(
            pastey::paste! {
                pub const [< $canonical_name _GUID>]: Guid = uguid::guid!($uuid);
            }

            pub const $canonical_name: UEFIProtocolInfo = UEFIProtocolInfo {
                name: stringify!($canonical_name),
                guid: uguid::guid!($uuid),
                summary: $summary
            };
        )*

        static ALL_PROTOCOLS: &[UEFIProtocolInfo] = &[
            $( $canonical_name, )*
        ];

        impl UEFIProtocolInfo {
            pub const fn by_guid(guid: Guid) -> Option<&'static Self> {
                let b = guid.to_bytes();

                let mut i = 0;
                'protocols: while i < ALL_PROTOCOLS.len() {
                    let a = ALL_PROTOCOLS[i].guid.to_bytes();

                    let mut j = 0;
                    while j < 16 {
                        if a[j] != b[j] {
                            i += 1;
                            continue 'protocols;
                        }
                        j += 1;
                    }

                    return Some(&ALL_PROTOCOLS[i]);
                }

                None
            }
        }
    };
}

define_protocols! {
    // DO NOT EDIT MANUALLY
    // -------------------------------------------------------
    // Automatically generated by running parser/extract_protocols.py
    // #######################################################
    EFI_ABSOLUTE_POINTER_PROTOCOL => "8d59d32b-c655-4ae9-9b15-f25904992a43" => r#"Provides services that allow information about an absolute pointer device to be retrieved."#,
    EFI_ACPI_TABLE_PROTOCOL => "ffe06bdd-6107-46a6-7bb2-5a9c7ec5275c" => r#"This protocol may be used to install or remove an ACPI table from a platform."#,
    EFI_ADAPTER_INFORMATION_PROTOCOL => "e5dd1403-d622-c24e-8488-c71b17f5e802" => r#"Since this protocol will return and set information for the adapter, the adapter device driver must publish the EFI_ADAPTER_INFORMATION_PROTOCOL. There are many kinds of adapters. The set and get adapter information functions should be used to determine the current state of the adapter, or to set a state for an adapter, like device speed."#,
    EFI_ARP_PROTOCOL => "f4b427bb-ba21-4f16-bc4e-43e416ab619c" => r#"ARP is used to resolve local network protocol addresses into network hardware addresses."#,
    EFI_ARP_SERVICE_BINDING_PROTOCOL => "f44c00ee-1f2c-4a00-aa09-1c9f3e0800a3" => r#"The ARPSBP is used to locate communication devices that are supported by an ARP driver and to create and destroy instances of the ARP child protocol driver. The EFI Service Binding Protocol in EFI Services Binding defines the generic Service Binding Protocol functions. This section discusses the details that are specific to the ARP."#,
    EFI_ATA_PASS_THRU_PROTOCOL => "1d3de7f0-0807-424f-aa69-11a54e19a46f" => r#"Provides services that allow ATA commands to be sent to ATA Devices attached to an ATA controller. Packet-based commands would be sent to ATAPI devices only through the Extended SCSI Pass Thru Protocol. While the ATA_PASS_THRU interface would expose an interface to the underlying ATA devices on an ATA controller, EXT_SCSI_PASS_THRU is responsible for exposing a packet-based command interface for the ATAPI devices on the same ATA controller."#,
    EFI_AUTHENTICATION_INFO_PROTOCOL => "7671d9d0-53db-4173-aa69-2327f21f0bc7" => r#"This protocol is used on any device handle to obtain authentication information associated with the physical or logical device."#,
    EFI_BIS_PROTOCOL => "0b64aab0-5429-11d4-9816-00a0c91fadcf" => r#"The EFI_BIS_PROTOCOL is used to check a digital signature of a data block against a digital certificate for the purpose of an integrity and authorization check."#,
    EFI_BLOCK_IO2_PROTOCOL => "a77b2472-e282-4e9f-a245-c2c0e27bbcc1" => r#"This protocol provides control over block devices."#,
    EFI_BLOCK_IO_CRYPTO_PROTOCOL => "a00490ba-3f1a-4b4c-ab90-4fa99726a1e8" => r#"The UEFI Inline Cryptographic Interface protocol provides services to abstract access to inline cryptographic capabilities. The usage model of this protocol is similar to the one of the EFI_STORAGE_SECURITY_COMMAND_PROTOCOL where FDE (Full Disk Encryption) solutions leave ESP partition unprotected (unencrypted) allowing storage clients to continue using EFI_BLOCK_IO_PROTOCOL or EFI_BLOCK_IO2_PROTOCOL protocol interfaces to load OS boot components from ESP partition. For other partitions boot apps (including OS boot app) that are enlightened to take advantage of inline cryptographic capability will be empowered to use this new protocol."#,
    EFI_BLOCK_IO_PROTOCOL => "964e5b21-6459-11d2-8e39-00a0c969723b" => r#"This protocol provides control over block devices."#,
    EFI_BLUETOOTH_ATTRIBUTE_PROTOCOL => "898890e9-84b2-4f3a-8c58-d8577813e0ac" => r#"This protocol provides service for Bluetooth ATT (Attribute Protocol) and GATT (Generic Attribute Profile) based protocol interfaces."#,
    EFI_BLUETOOTH_ATTRIBUTE_SERVICE_BINDING_PROTOCOL => "5639867a-8c8e-408d-ac2f-4b61bdc0bbbb" => r#"The EFI Bluetooth ATTRIBUTE Service Binding Protocol is used to locate EFI Bluetooth ATTRIBUTE Protocol drivers to create and destroy child of the driver to communicate with other Bluetooth device by using Bluetooth ATTRIBUTE protocol."#,
    EFI_BLUETOOTH_CONFIG_PROTOCOL => "62960cf3-40ff-4263-a77c-dfdebd191b4b" => r#"This protocol abstracts user interface configuration for Bluetooth device."#,
    EFI_BLUETOOTH_HC_PROTOCOL => "b3930571-beba-4fc5-9203-9427242e6a43" => r#"This protocol abstracts the Bluetooth host controller layer.message transmit and receive."#,
    EFI_BLUETOOTH_IO_PROTOCOL => "467313de-4e30-43f1-943e-323f89845db5" => r#"This protocol provides service for Bluetooth L2CAP (Logical Link Control and Adaptation Protocol) and SDP (Service Discovery Protocol)."#,
    EFI_BLUETOOTH_IO_SERVICE_BINDING_PROTOCOL => "388278d3-7b85-42f0-aba9-fb4bfd69f5ab" => r#"The EFI Bluetooth IO Service Binding Protocol is used to locate EFI Bluetooth IO Protocol drivers to create and destroy child of the driver to communicate with other Bluetooth device by using Bluetooth IO protocol."#,
    EFI_BLUETOOTH_LE_CONFIG_PROTOCOL => "8f76da58-1f99-4275-a4ec-4756515b1ce8" => r#"This protocol abstracts user interface configuration for BluetoothLe device."#,
    EFI_BOOT_MANAGER_POLICY_PROTOCOL => "fedf8e0c-e147-11e3-9903-b8e8562cbafa" => r#"This protocol is used by EFI Applications to request the UEFI Boot Manager to connect devices using platform policy."#,
    EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL => "3bc1b285-8a15-4a82-aabf-4d7d13fb3265" => r#"This protocol matches one or more drivers to a controller. This protocol is produced by a bus driver, and it is installed on the child handles of buses that require a bus specific algorithm for matching drivers to controllers. This protocol is used by the EFI_BOOT_SERVICES.ConnectController() boot service to select the best driver for a controller. All of the drivers returned by this protocol have a higher precedence than drivers found in the general EFI Driver Binding search algorithm, but a lower precedence than those drivers returned by the EFI Platform Driver Override Protocol. If more than one driver image handle is returned by this protocol, then the drivers image handles are returned in order from highest precedence to lowest precedence."#,
    EFI_CC_MEASUREMENT_PROTOCOL => "96751a3d-72f4-41a6-a794-ed5d0e67ae6b" => r#"This protocol abstracts the confidential computing (CC) measurement operation in UEFI guest environment."#,
    EFI_COMPONENT_NAME2_PROTOCOL => "6a7a5cff-e8d9-4f70-bada-75ab3025ce14" => r#"Used to retrieve user readable names of drivers and controllers managed by UEFI Drivers."#,
    EFI_COMPONENT_NAME_PROTOCOL => "6a7a5cff-e8d9-4f70-bada-75ab3025ce14" => r#"Used to retrieve user readable names of drivers and controllers managed by UEFI Drivers."#,
    EFI_CONFIG_KEYWORD_HANDLER_PROTOCOL => "0a8badd5-03b8-4d19-b128-7b8f0edaa596" => r#"The EFI_CONFIG_KEYWORD_HANDLER_PROTOCOL provides the mechanism to set and get the values associated with a keyword exposed through a x-UEFI- prefixed configuration language namespace."#,
    EFI_DEBUGPORT_PROTOCOL => "eba4e8d2-3858-41ec-a281-2647ba9660d0" => r#"This protocol provides the communication link between the debug agent and the remote host."#,
    EFI_DEBUG_SUPPORT_PROTOCOL => "2755590c-6f3c-42fa-9ea4-a3ba543cda25" => r#"This protocol provides the services to allow the debug agent to register callback functions that are called either periodically or when specific processor exceptions occur."#,
    EFI_DECOMPRESS_PROTOCOL => "d8117cfe-94a6-11d4-9a3a-0090273fc14d" => r#"Provides a decompression service."#,
    EFI_DEFERRED_IMAGE_LOAD_PROTOCOL => "15853d7c-3ddf-43e0-a1cb-ebf85b8f872c" => r#"Enumerates images whose load was deferred due to security considerations."#,
    EFI_DEVICE_PATH_FROM_TEXT_PROTOCOL => "05c99a21-c70f-4ad2-8a5f-35df3343f51e" => r#"Convert text to device paths and device nodes."#,
    EFI_DEVICE_PATH_PROTOCOL => "09576e91-6d3f-11d2-8e39-00a0c969723b" => r#"Can be used on any device handle to obtain generic path/location information concerning the physical device or logical device. If the handle does not logically map to a physical device, the handle may not necessarily support the device path protocol. The device path describes the location of the device the handle is for. The size of the Device Path can be determined from the structures that make up the Device Path."#,
    EFI_DEVICE_PATH_TO_TEXT_PROTOCOL => "8b843e20-8132-4852-90cc-551a4e4a7f1c" => r#"Convert device nodes and paths to text."#,
    EFI_DEVICE_PATH_UTILITIES_PROTOCOL => "0379be4e-d706-437d-b037-edb82fb772a4" => r#"Creates and manipulates device paths and device nodes."#,
    EFI_DHCP4_PROTOCOL => "8a219718-4ef5-4761-91c8-c0f04bda9e56" => r#"This protocol is used to collect configuration information for the EFI IPv4 Protocol drivers and to provide DHCPv4 server and PXE boot server discovery services."#,
    EFI_DHCP4_SERVICE_BINDING_PROTOCOL => "9d9a39d8-bd42-4a73-a4d5-8ee94be11380" => r#"The EFI DHCPv4 Service Binding Protocol is used to locate communication devices that are supported by an EFI DHCPv4 Protocol driver and to create and destroy EFI DHCPv4 Protocol child driver instances that can use the underlying communications device."#,
    EFI_DHCP6_PROTOCOL => "87c8bad7-0595-4053-8297-dede395f5d5b" => r#"The EFI DHCPv6 Protocol is used to get IPv6 addresses and other configuration parameters from DHCPv6 servers."#,
    EFI_DHCP6_SERVICE_BINDING_PROTOCOL => "9fb9a8a1-2f4a-43a6-889c-d0f7b6c47ad5" => r#"The EFI DHCPv6 Service Binding Protocol is used to locate communication devices that are supported by an EFI DHCPv6 Protocol driver and to create and destroy EFI DHCPv6 Protocol child instances that can use the underlying communications device."#,
    EFI_DISK_IO2_PROTOCOL => "151c8eae-7f2c-472c-9e54-9828194f6a88" => r#"This protocol is used to abstract Block I/O interfaces in a non-blocking manner."#,
    EFI_DISK_IO_PROTOCOL => "ce345171-ba0b-11d2-8e4f-00a0c969723b" => r#"This protocol is used to abstract Block I/O interfaces."#,
    EFI_DNS4_PROTOCOL => "ae3d28cc-e05b-4fa1-a011-7eb55a3f1401" => r#"This protocol provides the function to get the host name and address mapping, also provides pass through interface to retrieve arbitrary information from DNS. The EFI_DNS4_Protocol is primarily intended to retrieve host addresses using the standard DNS protocol (RFC1035), and support for this protocol is required. Implementations may optionally also support local network name resolution methods such as LLMNR (RFC4795) however DNS queries shall always take precedence, and any use of local network name protocols would be restricted to cases where resolution using DNS protocol fails. As stated above, all instances of EFI_DNS4_Protocol will utilize a common DNS cache containing the successful results of previous queries on any interface. However, it should be noted that every instance of EFI_DNS4_Protocol is associated with a specific network device or interface, and that all network actions initiated using a specific instance of the DNS protocol will occur only via use of the associated network interface. This means, in a system with multiple network interfaces, that a specific DNS server will often only be reachable using a specific network instance, and therefore the protocol user will need to take steps to ensure the DNS instance associated with the proper network interface is used. Or alternatively, the caller may perform DNS functions against all interfaces until successful result is achieved."#,
    EFI_DNS4_SERVICE_BINDING_PROTOCOL => "b625b186-e063-44f7-8905-6a74dc6f52b4" => r#"The DNSv4SB is used to locate communication devices that are supported by a DNS driver and to create and destroy instances of the DNS child protocol driver. The EFI Service Binding Protocol in EFI Services Binding defines the generic Service Binding Protocol functions. This section discusses the details that are specific to the DNSv4."#,
    EFI_DNS6_PROTOCOL => "ca37bc1f-a327-4ae9-828a-8c40d8506a17" => r#"This protocol provides the function to get the host name and address mapping, also provide pass through interface to retrieve arbitrary information from DNSv6. The EFI_DNS6_Protocol is primarily intended to retrieve host addresses using the standard DNS protocol (RFC3596), and support for this protocol is required. Implementations may optionally also support local network name resolution methods such as LLMNR (RFC4795) however DNS queries shall always take precedence, and any use of local network name protocols would be restricted to cases where resolution using DNS protocol fails. As stated above, all instances of EFI_DNS6_Protocol will utilize a common DNS cache containing the successful results of previous queries on any interface. However, it should be noted that every instance of EFI_DNS6_Protocol is associated with a specific network device or interface, and that all network actions initiated using a specific instance of the DNS protocol will occur only via use of the associated network interface. This means, in a system with multiple network interfaces, that a specific DNS server will often only be reachable using a specific network instance, and therefore the protocol user will need to take steps to ensure the DNS instance associated with the proper network interface is used. Or alternatively, the caller may perform DNS functions against all interfaces until successful result is achieved."#,
    EFI_DNS6_SERVICE_BINDING_PROTOCOL => "7f1647c8-b76e-44b2-a565-f70ff19cd19e" => r#"The DNSv6SB is used to locate communication devices that are supported by a DNS driver and to create and destroy instances of the DNS child protocol driver. The EFI Service Binding Protocol in EFI Services Binding defines the generic Service Binding Protocol functions. This section discusses the details that are specific to the DNSv6."#,
    EFI_DRIVER_BINDING_PROTOCOL => "18a031ab-b443-4d1a-a5c0-0c09261e9f71" => r#"Provides the services required to determine if a driver supports a given controller. If a controller is supported, then it also provides routines to start and stop the controller."#,
    EFI_DRIVER_DIAGNOSTICS2_PROTOCOL => "4d330321-025f-4aac-90d8-5ed900173b63" => r#"Used to perform diagnostics on a controller that a UEFI"#,
    EFI_DRIVER_DIAGNOSTICS_PROTOCOL => "4d330321-025f-4aac-90d8-5ed900173b63" => r#"Used to perform diagnostics on a controller that a UEFI"#,
    EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL => "b1ee129e-da36-4181-91f8-04a4923766a7" => r#"When installed, the Driver Family Override Protocol informs the UEFI Boot Service ConnectController() that this driver is higher priority than the list of drivers returned by the Bus Specific Driver Override Protocol."#,
    EFI_DRIVER_HEALTH_PROTOCOL => "2a534210-9280-41d8-ae79-cada01a2b127" => r#"When installed, the Driver Health Protocol produces a collection of services that allow the health status for a controller to be retrieved. If a controller is not in a usable state, status messages may be reported to the user, repair operations can be invoked, and the user may be asked to make software and/or hardware configuration changes. All display, as well as interaction, with the user must be handled by the consumer of the Driver Health Protocol. The Driver Health Protocol must be installed onto the same handle as the associated Driver Binding handle."#,
    EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL => "5c198761-16a8-4e69-972c-89d67954f81d" => r#"Provides information about the version of the EFI specification that a driver is following. This protocol is required for EFI drivers that are on PCI and other plug in cards."#,
    EFI_EAP_CONFIGURATION_PROTOCOL => "e5b58dbb-7688-44b4-97bf-5f1d4b7cc8db" => r#"This protocol provides a way to set and get EAP configuration."#,
    EFI_EAP_MANAGEMENT2_PROTOCOL => "5e93c847-456d-40b3-a6b4-78b0c9cf7f20" => r#"This protocol provides the ability to configure and control EAPOL state machine, and retrieve the information, status and the statistics information of EAPOL state machine."#,
    EFI_EAP_MANAGEMENT_PROTOCOL => "bb62e663-625d-40b2-a088-bbe83623a245" => r#"This protocol provides the ability to configure and control EAPOL state machine, and retrieve the status and the statistics information of EAPOL state machine."#,
    EFI_EAP_PROTOCOL => "5d9f96db-e731-4caa-a00d-72e187cd7762" => r#"This protocol is used to abstract the ability to configure and extend the EAP framework."#,
    EFI_EBC_PROTOCOL => "13ac6dd1-73d0-11d4-b06b-00aa00bd6de7" => r#"This protocol provides the services that allow execution of EBC images."#,
    EFI_EDID_ACTIVE_PROTOCOL => "bd8c1056-9f36-44ec-92a8-a6337f817986" => r#"This protocol contains the EDID information for an active video output device. This is either the EDID information retrieved from the EFI_EDID_OVERRIDE_PROTOCOL if an override is available, or an identical copy of the EDID information from the EFI_EDID_DISCOVERED_PROTOCOL if no overrides are available."#,
    EFI_EDID_DISCOVERED_PROTOCOL => "1c0c34f6-d380-41fa-a049-8ad06c1a66aa" => r#"This protocol contains the EDID information retrieved from a video output device."#,
    EFI_EDID_OVERRIDE_PROTOCOL => "48ecb431-fb72-45c0-a922-f458fe040bd5" => r#"This protocol is produced by the platform to allow the platform to provide EDID information to the producer of the Graphics Output protocol."#,
    EFI_ERASE_BLOCK_PROTOCOL => "95a9a93e-a86e-4926-aaef-9918e772d987" => r#"This protocol provides the ability for a device to expose erase functionality. This optional protocol is installed on the same handle as the EFI_BLOCK_IO_PROTOCOL or EFI_BLOCK_IO2_PROTOCOL."#,
    EFI_EXT_SCSI_PASS_THRU_PROTOCOL => "143b7632-b81b-4cb7-abd3-b625a5b9bffe" => r#"Provides services that allow SCSI Pass Thru commands to be sent to SCSI devices attached to a SCSI channel. It also allows packet-based commands (ATAPI cmds) to be sent to ATAPI devices attached to a ATA controller."#,
    EFI_FIRMWARE_MANAGEMENT_PROTOCOL => "86c77a67-0b97-4633-a187-49104d0685c7" => r#"Firmware Management application invokes this protocol to manage device firmware."#,
    EFI_FORM_BROWSER2_PROTOCOL => "b9d4c360-bcfb-4f9b-9298-53c136982258" => r#"The EFI_FORM_BROWSER2_PROTOCOL is the interface to the UEFI configuration driver. This interface will allow the caller to direct the configuration driver to use either the HII database or use the passed-in packet of data."#,
    EFI_FTP4_PROTOCOL => "eb338826-681b-4295-b356-2b364c757b09" => r#"The EFI FTPv4 Protocol provides basic services for client-side FTP (File Transfer Protocol) operations."#,
    EFI_FTP4_SERVICE_BINDING_PROTOCOL => "0faaecb1-226e-4782-aace-7db9bcbf4daf" => r#"The EFI_FTP4_SERVICE_BINDING_PROTOCOL is used to locate communication devices that are supported by an EFI FTPv4 Protocol driver and to create and destroy instances of the EFI FTPv4 Protocol child protocol driver that can use the underlying communication device."#,
    EFI_GRAPHICS_OUTPUT_PROTOCOL => "9042a9de-23dc-4a38-96fb-7aded080516a" => r#"Provides a basic abstraction to set video modes and copy pixels to and from the graphics controller’s frame buffer. The linear address of the hardware frame buffer is also exposed so software can write directly to the video hardware."#,
    EFI_HASH2_PROTOCOL => "55b1d734-c5e1-49db-9647-b16afb0e305b" => r#"This protocol describes hashing functions for which the algorithm-required message padding and finalization are performed by the supporting driver."#,
    EFI_HASH2_SERVICE_BINDING_PROTOCOL => "da836f8d-217f-4ca0-99c2-1ca4e16077ea" => r#"The EFI Hash2 Service Binding Protocol is used to locate EFI_HASH2_PROTOCOL hashing services support provided by a driver and create and destroy instances of the EFI_HASH2_PROTOCOL Protocol so that a multiple drivers can use the underlying hashing services. The EFI Service Binding Protocol that is defined in EFI Services Binding defines the generic Service Binding Protocol functions. This section discusses the details that are specific to the EFI Hash Protocol."#,
    EFI_HASH_PROTOCOL => "c5184932-dba5-46db-a5ba-cc0bda9c1435" => r#"This protocol describes standard hashing functions."#,
    EFI_HASH_SERVICE_BINDING_PROTOCOL => "42881c98-a4f3-44b0-a39d-dfa18667d8cd" => r#"The EFI Hash Service Binding Protocol is used to locate hashing services support provided by a driver and create and destroy instances of the EFI Hash Protocol so that a multiple drivers can use the underlying hashing services. The EFI Service Binding Protocol that is defined in EFI Services Binding defines the generic Service Binding Protocol functions. This section discusses the details that are specific to the EFI Hash Protocol."#,
    EFI_HII_CONFIG_ACCESS_PROTOCOL => "330d4706-f2a0-4e4f-a369-b66fa8d54385" => r#"The EFI HII configuration routing protocol invokes this type of protocol when it needs to forward requests to a driver's configuration handler. This protocol is published by drivers providing and receiving configuration data from HII. The ExtractConfig() and RouteConfig() functions are typically invoked by the driver which implements the HII Configuration Routing Protocol. The Callback() function is typically invoked by the Forms Browser. If the protocol functions modify active form set, they must not change layout and size of the existing variable stores. The forms browser processes updated IFR package in accordance with the following rules: NOTE: If browser action implies saving of the modified questions values, the browser will use uncommitted data associated with the old form set instance. The HII Configuration Access implementation is responsible for properly handling such requests. NOTE: Changing layout or size of the existing variable stores during form set update is not allowed and can lead to unpredictable results."#,
    EFI_HII_CONFIG_ROUTING_PROTOCOL => "587e72d7-cc50-4f79-8209-ca291fc1a10f" => r#"The EFI HII Configuration Routing Protocol manages the movement of configuration data from drivers to configuration applications. It then serves as the single point to receive configuration information from configuration applications, routing the results to the appropriate drivers."#,
    EFI_HII_DATABASE_PROTOCOL => "ef9fc172-a1b2-4693-b327-6d32fc416042" => r#"Database manager for HII-related data structures."#,
    EFI_HII_FONT_EX_PROTOCOL => "849e6875-db35-4df8-b41e-c8f33718073f" => r#"Interfaces which retrieve the font information."#,
    EFI_HII_FONT_GLYPH_GENERATOR_PROTOCOL => "f7102853-7787-4dc2-a8a8-21b5dd05c89b" => r#"EFI HII Font glyph generator protocol generates the glyph of the character according to the given font information."#,
    EFI_HII_FONT_PROTOCOL => "e9ca4775-8657-47fc-97e7-7ed65a084324" => r#"Interfaces which retrieve font information."#,
    EFI_HII_IMAGE_DECODER_PROTOCOL => "9e66f251-727c-418c-bfd6-c2b4252818ea" => r#"Provides the image decr for specific image file formats."#,
    EFI_HII_IMAGE_EX_PROTOCOL => "1a1241e6-8f19-41a9-bc0e-e8ef39e06546" => r#"Protocol which allows access to the images in the images database"#,
    EFI_HII_IMAGE_PROTOCOL => "31a6406a-6bdf-4e46-b2a2-ebaa89c40920" => r#"Protocol which allow access to images in the images database."#,
    EFI_HII_POPUP_PROTOCOL => "4311edc0-6054-46d4-9e40-893ea952fccc" => r#"This protocol provides services to display a popup window. The protocol is typically produced by the forms browser and consumed by a driver’s callback handler."#,
    EFI_HII_STRING_PROTOCOL => "0fd96974-23aa-4cdc-b9cb-98d17750322a" => r#"Interfaces which manipulate string data."#,
    EFI_HTTP_BOOT_CALLBACK_PROTOCOL => "ba23b311-343d-11e6-9185-5820b1d65299" => r#"Protocol that is invoked when the HTTP Boot driver is about to transmit or has received a packet."#,
    EFI_HTTP_PROTOCOL => "7a59b29b-910b-4171-8242-a85a0df25b5b" => r#""#,
    EFI_HTTP_SERVICE_BINDING_PROTOCOL => "bdc8e6af-d9bc-4379-a72a-e0c4e75dae1c" => r#"The HTTPSB is used to locate communication devices that are supported by a HTTP driver and to create and destroy instances of the HTTP child protocol driver. The EFI Service Binding Protocol in EFI Services Binding defines the generic Service Binding Protocol functions. This section discusses the details that are specific to the HTTP."#,
    EFI_HTTP_UTILITIES_PROTOCOL => "3e35c163-4074-45dd-431e-23989dd86b32" => r#""#,
    EFI_IP4_CONFIG2_PROTOCOL => "5b446ed1-e30b-4faa-871a-3654eca36080" => r#"The EFI_IP4_CONFIG2_PROTOCOL provides the mechanism to set and get various types of configurations for the EFI IPv4 network stack."#,
    EFI_IP4_PROTOCOL => "41d94cd2-35b6-455a-8258-d4e51334aadd" => r#"The EFI IPv4 Protocol implements a simple packet-oriented interface that can be used by drivers, daemons, and applications to transmit and receive network packets."#,
    EFI_IP4_SERVICE_BINDING_PROTOCOL => "c51711e7-b4bf-404a-bfb8-0a048ef1ffe4" => r#"The EFI IPv4 Service Binding Protocol is used to locate communication devices that are supported by an EFI IPv4 Protocol driver and to create and destroy instances of the EFI IPv4 Protocol child protocol driver that can use the underlying communications device."#,
    EFI_IP6_CONFIG_PROTOCOL => "937fe521-95ae-4d1a-8929-48bcd90ad31a" => r#"The EFI_IP6_CONFIG_PROTOCOL provides the mechanism to set and get various types of configurations for the EFI IPv6 network stack."#,
    EFI_IP6_PROTOCOL => "2c8759d5-5c2d-66ef-925f-b66c101957e2" => r#"The EFI IPv6 Protocol implements a simple packet-oriented interface that can be used by drivers, daemons, and applications to transmit and receive network packets."#,
    EFI_IP6_SERVICE_BINDING_PROTOCOL => "ec835dd3-fe0f-617b-a621-b350c3e13388" => r#"The EFI IPv6 Service Binding Protocol is used to locate communication devices that are supported by an EFI IPv6 Protocol driver and to create and destroy EFI IPv6 Protocol child instances of the IP6 driver that can use the underlying communications device."#,
    EFI_IPSEC2_PROTOCOL => "a3979e64-ace8-4ddc-bc07-4d66b8fd0977" => r#"The EFI_IPSEC2_PROTOCOL is used to abstract the ability to deal with the individual packets sent and received by the host and provide packet-level security for IP datagram.."#,
    EFI_IPSEC_CONFIG_PROTOCOL => "ce5e5929-c7a3-4602-ad9e-c9daf94ebfcf" => r#"The EFI_IPSEC_CONFIG_PROTOCOL provides the mechanism to set and retrieve security and policy related information for the EFI IPsec protocol driver."#,
    EFI_IPSEC_PROTOCOL => "dfb386f7-e100-43ad-9c9a-ed90d08a5e12" => r#"The EFI_IPSEC_PROTOCOL is used to abstract the ability to deal with the individual packets sent and received by the host and provide packet-level security for IP datagram."#,
    EFI_ISCSI_INITIATOR_NAME_PROTOCOL => "59324945-ec44-4c0d-b1cd-9db139df070c" => r#"iSCSI Initiator Name Protocol for setting and obtaining the iSCSI Initiator Name."#,
    EFI_KEY_MANAGEMENT_SERVICE_PROTOCOL => "ec3a978d-7c4e-48fa-9abe-6ad91cc8f811" => r#"The Key Management Service (KMS) protocol provides services to generate, store, retrieve, and manage cryptographic keys. The intention is to specify a simple generic protocol that could be used for many implementations. The management keys have a simple construct - they consist of key identifier and key data, both of variable size. A driver implementing the protocol may need to provide basic key service that consists of a key store and cryptographic key generation capability. It may connect to an external key server over the network, or to a Hardware Security Module (HSM) attached to the system it runs on, or anything else that is capable of providing the key management service. Authentication and access control is not addressed by this protocol. It is assumed it is addressed at the system level and done by the driver implementing the protocol, if applicable to the implementation."#,
    EFI_LOADED_IMAGE_DEVICE_PATH_PROTOCOL => "bc62157e-3e33-4fec-9920-2d3b36d750df" => r#"When installed, the Loaded Image Device Path Protocol specifies the device path that was used when a PE/COFF image was loaded through the EFI Boot Service LoadImage()."#,
    EFI_LOADED_IMAGE_PROTOCOL => "5b1b31a1-9562-11d2-8e3f-00a0c969723b" => r#"Can be used on any image handle to obtain information about the loaded image."#,
    EFI_LOAD_FILE2_PROTOCOL => "4006c0c1-fcb3-403e-996d-4a6c8724e06d" => r#"Used to obtain files from arbitrary devices but are not used as boot options."#,
    EFI_LOAD_FILE_PROTOCOL => "56ec3091-954c-11d2-8e3f-00a0c969723b" => r#"Used to obtain files, that are primarily boot options, from arbitrary devices."#,
    EFI_MANAGED_NETWORK_PROTOCOL => "7ab33a91-ace5-4326-b572-e7ee33d39f16" => r#"The MNP is used by network applications (and drivers) to perform raw (unformatted) asynchronous network packet I/O."#,
    EFI_MANAGED_NETWORK_SERVICE_BINDING_PROTOCOL => "f36ff770-a7e1-42cf-9ed2-56f0f271f44c" => r#"The MNSBP is used to locate communication devices that are supported by an MNP driver and to create and destroy instances of the MNP child protocol driver that can use the underlying communications device. The EFI Service Binding Protocol in EFI Services Binding defines the generic Service Binding Protocol functions. This section discusses the details that are specific to the MNP."#,
    EFI_MEMORY_ATTRIBUTE_PROTOCOL => "f4560cf6-40ec-4b4a-a192-bf1d57d0b189" => r#"This protocol abstracts the memory attributes setting or getting in UEFI environment."#,
    EFI_MTFTP4_PROTOCOL => "78247c57-63db-4708-99c2-a8b4a9a61f6b" => r#"The EFI MTFTPv4 Protocol provides basic services for client-side unicast and/or multicast TFTP operations."#,
    EFI_MTFTP4_SERVICE_BINDING_PROTOCOL => "02e800be-8f01-4aa6-946b-d71388e1833f" => r#"The EFI MTFTPv4 Service Binding Protocol is used to locate communication devices that are supported by an EFI MTFTPv4 Protocol driver and to create and destroy instances of the EFI MTFTPv4 Protocol child protocol driver that can use the underlying communications device."#,
    EFI_MTFTP6_PROTOCOL => "bf0a78ba-ec29-49cf-a1c9-7ae54eab6a51" => r#"The EFI MTFTPv6 Protocol provides basic services for client-side unicast and/or multicast TFTP operations."#,
    EFI_MTFTP6_SERVICE_BINDING_PROTOCOL => "d9760ff3-3cca-4267-80f9-7527fafa4223" => r#"The EFI MTFTPv6 Service Binding Protocol is used to locate communication devices that are supported by an EFI MTFTPv6 Protocol driver and to create and destroy instances of the EFI MTFTPv6 Protocol child instance that can use the underlying communications device."#,
    EFI_NETWORK_INTERFACE_IDENTIFIER_PROTOCOL => "1aced566-76ed-4218-bc81-767f1f977a89" => r#"An optional protocol that is used to describe details about the software layer that is used to produce the Simple Network Protocol."#,
    EFI_NVDIMM_LABEL_PROTOCOL => "d40b6b80-97d5-4282-bb1d-223a16918058" => r#"Provides services that allow management of labels contained in a Label Storage Area that are associated with a specific NVDIMM Device Path. The labels describe how the data on the NVDIMM is organized in to namespaces, the layout being utilized, logical block size, unique label identifier, label state, etc."#,
    EFI_NVM_EXPRESS_PASS_THRU_PROTOCOL => "52c78312-8edc-4233-98f2-1a1aa5e388a5" => r#"This protocol provides services that allow NVM Express commands to be sent to an NVM Express controller or to a specific namespace in a NVM Express controller. This protocol interface is optimized for storage."#,
    EFI_PARTITION_INFO_PROTOCOL => "8cf2f62c-bc9b-4821-808d-ec9ec421a1a0" => r#"Installed along with EFI_BLOCK_IO_PROTOCOL for logical partitions. The PARTITION_INFORMATION_PROTOCOL provides cached partition information for MBR and GPT partition types. Set System to 1 for partition identified as EFI_SYSTEM_PARTITIONs, otherwise set System to 0. Set Type to PARTITION_TYPE_OTHER for partitions that are not GPT or MBR to indicate no cached data."#,
    EFI_PCI_IO_PROTOCOL => "4cf5b200-68b8-4ca5-9eec-b23e3f50029a" => r#"Provides the basic Memory, I/O, PCI configuration, and DMA interfaces that a driver uses to access its PCI controller."#,
    EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL => "2f707ebb-4a1a-11d4-9a38-0090273fc14d" => r#"Provides the basic Memory, I/O, PCI configuration, and DMA interfaces that are used to abstract accesses to PCI controllers behind a PCI Root Bridge Controller."#,
    EFI_PKCS7_VERIFY_PROTOCOL => "47889fb2-d671-4fab-a0ca-df0e44df70d6" => r#"EFI_PKCS7_VERIFY_PROTOCOL (See: http://tools.ietf.org/html/rfc2315 ) may be used to verify data signed with PKCS#7 formatted authentication. The PKCS#7 data to be verified must be binary DER encoded. Additional information on the supported ASN.1 formatting is provided below. Drivers that supply PKCS7 verification function should publish the | EFI_PKCS7_VERIFY_PROTOCOL. Drivers wishing to use the | EFI_PKCS7_VERIFY_PROTOCOL may get a reference with LocateProtocol()."#,
    EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL => "6b30c738-a391-11d4-9a3b-0090273fc14d" => r#"This protocol matches one or more drivers to a controller. A platform driver produces this protocol, and it is installed on a separate handle. This protocol is used by the EFI_BOOT_SERVICES.ConnectController() boot service to select the best driver for a controller. All of the drivers returned by this protocol have a higher precedence than drivers found from an EFI Bus Specific Driver Override Protocol or drivers found from the general UEFI driver Binding search algorithm. If more than one driver is returned by this protocol, then the drivers are returned in order from highest precedence to lowest precedence."#,
    EFI_PLATFORM_TO_DRIVER_CONFIGURATION_PROTOCOL => "642cd590-8059-4c0a-a958-c5ec07d23c4b" => r#"Used to retrieve configuration information for a device that a UEFI driver is about to start."#,
    EFI_PXE_BASE_CODE_CALLBACK_PROTOCOL => "245dca21-fb7b-11d3-8f01-00a0c969723b" => r#"Protocol that is invoked when the PXE Base Code Protocol is about to transmit, has received, or is waiting to receive a packet."#,
    EFI_PXE_BASE_CODE_PROTOCOL => "03c4e603-ac28-11d3-9a2d-0090273fc14d" => r#"The EFI_PXE_BASE_CODE_PROTOCOL is used to control PXE-compatible devices. The features of these devices are defined in the Preboot Execution Environment (PXE) Specification. An EFI_PXE_BASE_CODE_PROTOCOL will be layered on top of an EFI_MANAGED_NETWORK_PROTOCOL protocol in order to perform packet level transactions. The EFI_PXE_BASE_CODE_PROTOCOL handle also supports the See EFI_LOAD_FILE_PROTOCOL protocol. This provides a clean way to obtain control from the boot manager if the boot path is from the remote device."#,
    EFI_RAM_DISK_PROTOCOL => "ab38a0df-6873-44a9-87e6-d4eb56148449" => r#"RAM disk aware application invokes this protocol to register/unregister a specified RAM disk."#,
    EFI_REDFISH_DISCOVER_PROTOCOL => "5db12509-4550-4347-96b3-73c0ff6e869f" => r#"This protocol is utilized by EFI Redfish clients to acquire the list of Redfish services provided on platform or network."#,
    EFI_REGULAR_EXPRESSION_PROTOCOL => "b3f79d9a-436c-dc11-b052-cd85df524ce6" => r#""#,
    EFI_RESET_NOTIFICATION_PROTOCOL => "9da34ae0-eaf9-4bbf-8ec3-fd60226c44be" => r#"This protocol provides services to register for a notification when ResetSystem is called."#,
    EFI_REST_EX_PROTOCOL => "55648b91-0e7d-40a3-a9b3-a815d7eadf97" => r#""#,
    EFI_REST_EX_SERVICE_BINDING_PROTOCOL => "456bbe01-99d0-45ea-bb5f-16d84bedc559" => r#"The RESTEXSB is used to locate the REST services those are supported by a REST EX driver instances and to create and destroy instances of REST EX child protocol driver. The EFI Service Binding Protocol in EFI Service Binding Protocol defines the generic Service Binding Protocol functions. This section discusses the details that are specific to the REST EX."#,
    EFI_REST_JSON_STRUCTURE_PROTOCOL => "a9a048f6-48a0-4714-b7da-a9ad87d4dac9" => r#"EFI REST JSON Structure Protocol provides function to converter producer for the registration of REST JSON resource structure converter. This protocol also provides functions of JSON-IN Structure-OUT and vice versa to converter consumer."#,
    EFI_REST_PROTOCOL => "0db48a36-4e54-ea9c-9b09-1ea5be3a660b" => r#""#,
    EFI_RNG_PROTOCOL => "3152bca5-eade-433d-862e-c01cdc291f44" => r#"This protocol provides standard RNG functions. It can be used to provide random bits for use in applications, or entropy for seeding other random number generators."#,
    EFI_SCSI_IO_PROTOCOL => "932f47e6-2362-4002-803e-3cd54b138f85" => r#"Provides services to manage and communicate with SCSI devices."#,
    EFI_SD_MMC_PASS_THRU_PROTOCOL => "716ef0d9-ff83-4f69-81e9-518bd39a8e70" => r#"This section provides a detailed description of the EFI_SD_MMC_PASS_THRU_PROTOCOL. The protocol provides services that allow SD/eMMC commands to be sent to an SD/eMMC controller. All interfaces anddefinitions from this section apply equally to SD and eMMC controllers. For the sake of brevity, the rest of this section refers only to SD devices and controllers and does not specifically mention eMMC devices and controllers."#,
    EFI_SERIAL_IO_PROTOCOL => "bb25cf6f-f1d4-11d2-9a0c-0090273fc1fd" => r#"This protocol is used to communicate with any type of character-based I/O device."#,
    EFI_SIMPLE_FILE_SYSTEM_PROTOCOL => "0964e5b2-6459-11d2-8e39-00a0c969723b" => r#"Provides a minimal interface for file-type access to a device."#,
    EFI_SIMPLE_NETWORK_PROTOCOL => "a19832b9-ac25-11d3-9a2d-0090273fc14d" => r#"The EFI_SIMPLE_NETWORK_PROTOCOL provides services to initialize a network interface, transmit packets, receive packets, and close a network interface."#,
    EFI_SIMPLE_POINTER_PROTOCOL => "31878c87-0b75-11d5-9a4f-0090273fc14d" => r#"Provides services that allow information about a pointer device to be retrieved."#,
    EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL => "dd9e7534-7762-4698-8c14-f58517a625aa" => r#"This protocol is used to obtain input from the ConsoleIn device. The EFI specification requires that the EFI_SIMPLE_TEXT_INPUT_PROTOCOL supports the same languages as the corresponding EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL."#,
    EFI_SIMPLE_TEXT_INPUT_PROTOCOL => "387477c1-69c7-11d2-8e39-00a0c969723b" => r#"This protocol is used to obtain input from the ConsoleIn device. The EFI specification requires that the EFI_SIMPLE_TEXT_INPUT_PROTOCOL supports the same languages as the corresponding EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL."#,
    EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL => "387477c2-69c7-11d2-8e39-00a0c969723b" => r#"This protocol is used to control text-based output devices."#,
    EFI_SMART_CARD_EDGE_PROTOCOL => "d317f29b-a325-4712-9bf1-c61954dc198c" => r#"Smart Card aware application invokes this protocol to get access to an inserted Smart Card in the reader."#,
    EFI_SMART_CARD_READER_PROTOCOL => "2a4d1adf-21dc-4b81-a42f-8b8ee2380060" => r#"Smart card aware application invokes this protocol to get access to an inserted smart card in the reader or to the reader itself."#,
    EFI_STORAGE_SECURITY_COMMAND_PROTOCOL => "c88b0b6d-0dfc-49a7-9cb4-49074b4c3a78" => r#"This protocol provides ability to send security protocol commands to mass storage devices."#,
    EFI_SUPPLICANT_PROTOCOL => "54fcc43e-aa89-4333-9a85-cdea24051e9e" => r#"This protocol provides services to process authentication and data encryption/decryption for security management."#,
    EFI_SUPPLICANT_SERVICE_BINDING_PROTOCOL => "45bcd98e-59ad-4174-9546-344a07485898" => r#"The EFI Supplicant Service Binding Protocol is used to locate EFI Supplicant Protocol drivers to create and destroy child of the driver to communicate with other host using Supplicant protocol."#,
    EFI_TAPE_IO_PROTOCOL => "1e93e633-d65a-459e-ab84-93d9ec266d18" => r#"The EFI Tape IO protocol provides services to control and access a tape device."#,
    EFI_TCP4_PROTOCOL => "65530bc7-a359-410f-b010-5aadc7ec2b62" => r#"The EFI TCPv4 Protocol provides services to send and receive data stream."#,
    EFI_TCP4_SERVICE_BINDING_PROTOCOL => "00720665-67eb-4a99-baf7-d3c33a1c7cc9" => r#"The EFI TCPv4 Service Binding Protocol is used to locate EFI TCPv4 Protocol drivers to create and destroy child of the driver to communicate with other host using TCP protocol."#,
    EFI_TCP6_PROTOCOL => "46e44855-bd60-4ab7-ab0d-a679b9447d77" => r#"The EFI TCPv6 Protocol provides services to send and receive data stream."#,
    EFI_TCP6_SERVICE_BINDING_PROTOCOL => "ec20eb79-6c1a-4664-9a0d-d2e4cc16d664" => r#"The EFI TCPv6 Service Binding Protocol is used to locate EFI TCPv6 Protocol drivers to create and destroy protocol child instance of the driver to communicate with other host using TCP protocol."#,
    EFI_TIMESTAMP_PROTOCOL => "afbfde41-2e6e-4262-ba65-62b9236e5495" => r#"The Timestamp protocol provides a platform independent interface for retrieving a high resolution timestamp counter."#,
    EFI_TLS_CONFIGURATION_PROTOCOL => "1682fe44-bd7a-4407-b7c7-dca37ca3922d" => r#"This protocol provides a way to set and get TLS configuration."#,
    EFI_TLS_PROTOCOL => "00ca959f-6cfa-4db1-95bc-e46c47514390" => r#"This protocol provides the ability to manage TLS session."#,
    EFI_TLS_SERVICE_BINDING_PROTOCOL => "952cb795-ff36-48cf-a249-4df486d6ab8d" => r#"The EFI TLS Service Binding Protocol is used to locate EFI TLS Protocol drivers to create and destroy child of the driver to communicate with other host using TLS protocol."#,
    EFI_UDP4_PROTOCOL => "3ad9df29-4501-478d-b1f8-7f7fe70e50f3" => r#"The EFI UDPv4 Protocol provides simple packet-oriented services to transmit and receive UDP packets."#,
    EFI_UDP4_SERVICE_BINDING_PROTOCOL => "83f01464-99bd-45e5-b383-af6305d8e9e6" => r#"The EFI UDPv4 Service Binding Protocol is used to locate communication devices that are supported by an EFI UDPv4 Protocol driver and to create and destroy instances of the EFI UDPv4 Protocol child protocol driver that can use the underlying communications device."#,
    EFI_UDP6_PROTOCOL => "4f948815-b4b9-43cb-8a33-90e060b34955" => r#"The EFI UDPv6 Protocol provides simple packet-oriented services to transmit and receive UDP packets."#,
    EFI_UDP6_SERVICE_BINDING_PROTOCOL => "66ed4721-3c98-4d3e-81e3-d03dd39a7254" => r#"The EFI UDPv6 Service Binding Protocol is used to locate communication devices that are supported by an EFI UDPv6 Protocol driver and to create and destroy instances of the EFI UDPv6 Protocol child instance that uses the underlying communications device."#,
    EFI_UFS_DEVICE_CONFIG_PROTOCOL => "b81bfab0-0eb3-4cf9-8465-7fa986361664" => r#"User invokes this protocol to access the UFS device descriptors/flags/attributes and configure UFS device behavior."#,
    EFI_UNICODE_COLLATION_PROTOCOL => "a4c751fc-23ae-4c3e-92e9-4964cf63f349" => r#"Is used to perform case-insensitive comparisons of strings."#,
    EFI_USB2_HC_PROTOCOL => "3e745226-9818-45b6-a2ac-d7cd0e8ba2bc" => r#"Provides basic USB host controller management, basic data transactions over USB bus, and USB root hub access."#,
    EFI_USBFN_IO_PROTOCOL => "32d2963a-fe5d-4f30-b633-6e5dc55803cc" => r#"Provides basic data transactions and basic USB controller management for a USB Function port."#,
    EFI_USB_IO_PROTOCOL => "2b2f68d6-0cd2-44cf-8e8b-bba20b1b5b75" => r#"Provides services to manage and communicate with USB devices."#,
    EFI_USER_CREDENTIAL2_PROTOCOL => "e98adb03-b8b9-4af8-ba20-26e9114cbce5" => r#"Provide support for a single class of credentials"#,
    EFI_USER_MANAGER_PROTOCOL => "6fd5b00c-d426-4283-9887-6cf5cf1cb1fe" => r#"Reports information about a user."#,
    EFI_VLAN_CONFIG_PROTOCOL => "9e23d768-d2f3-4366-9fc3-3a7aba864374" => r#"This protocol is to provide manageability interface for VLAN configuration."#,
    EFI_WIRELESS_MAC_CONNECTION_II_PROTOCOL => "1b0fb9bf-699d-4fdd-a7c3-2546681bf63b" => r#"The EFI_WIRELESS_MAC_CONNECTION_II_PROTOCOL provides network management service interfaces for 802.11 network stack. It is used by network applications (and drivers) to establish wireless connection with a wireless network."#,
    EFI_WIRELESS_MAC_CONNECTION_PROTOCOL => "0da55bc9-45f8-4bb4-8719-5224f18a4d45" => r#"This protocol provides management service interfaces of 802.11 MAC layer. It is used by network applications (and drivers) to establish wireless connection with an access point (AP)."#,
}

#[cfg(test)]
mod tests {
    use uguid::guid;

    use crate::protocols::{ALL_PROTOCOLS, UEFIProtocolInfo};

    #[test]
    pub fn find_some_protocols() {
        assert_eq!(
            UEFIProtocolInfo::by_guid(guid!("e98adb03-b8b9-4af8-ba20-26e9114cbce5")),
            Some(&super::EFI_USER_CREDENTIAL2_PROTOCOL)
        );
        assert_eq!(
            UEFIProtocolInfo::by_guid(guid!("1a1241e6-8f19-41a9-bc0e-e8ef39e06546")),
            Some(&super::EFI_HII_IMAGE_EX_PROTOCOL)
        );
        assert_eq!(
            UEFIProtocolInfo::by_guid(guid!("05c99a21-c70f-4ad2-8a5f-35df3343f51e")),
            Some(&super::EFI_DEVICE_PATH_FROM_TEXT_PROTOCOL)
        );
        assert_eq!(
            UEFIProtocolInfo::by_guid(guid!("e98adb03-b8b9-4af8-ba20-133713371337")),
            None
        );
        assert!(super::ALL_PROTOCOLS.len() >= 152);

        assert_eq!(
            super::EFI_DEVICE_PATH_FROM_TEXT_PROTOCOL.name,
            "EFI_DEVICE_PATH_FROM_TEXT_PROTOCOL"
        );
    }

    #[test]
    pub fn rule_out_parsing_mistakes() {
        for protocol in ALL_PROTOCOLS {
            assert!(!protocol.name.contains(" "));
            assert!(!protocol.summary.contains("ref:"));
        }
    }
}
